name: Android Build Cross-Platform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set ANDROID_SDK_ROOT environment variable
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: echo "ANDROID_SDK_ROOT=$HOME/Android/Sdk" >> $GITHUB_ENV

      - name: Install Android SDK command-line tools (Linux/macOS)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools.zip
          rm commandlinetools.zip
          pwd
          mv cmdline-tools latest
          ls -alh
      - name: Accept licenses (Linux/macOS)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          ls -alh $ANDROID_HOME/cmdline-tools/latest
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install SDK packages (Linux/macOS)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-36" "build-tools;36.0.0"

      - name: Grant execute permission for gradlew (Linux/macOS)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: chmod +x ./gradlew

      - name: Set ANDROID_SDK_ROOT for Windows
        if: runner.os == 'Windows'
        run: echo "ANDROID_SDK_ROOT=C:\\Users\\runneradmin\\AppData\\Local\\Android\\Sdk" >> $GITHUB_ENV

      - name: Install Android SDK command-line tools (Windows)
        if: runner.os == 'Windows'
        run: |
          Invoke-WebRequest -Uri https://dl.google.com/android/repository/commandlinetools-win-9477386_latest.zip -OutFile cmdline.zip
          Expand-Archive cmdline.zip -DestinationPath $Env:ANDROID_SDK_ROOT\cmdline-tools
          Remove-Item cmdline.zip
          Get-Location
          Rename-Item -Path '.\cmdline-tools' -NewName 'latest'
          Get-ChildItem -Force | Format-List
        shell: pwsh

      - name: Accept licenses (Windows)
        if: runner.os == 'Windows'
        run: yes | $Env:ANDROID_SDK_ROOT\cmdline-tools\latest\bin\sdkmanager --licenses

      - name: Install SDK packages (Windows)
        if: runner.os == 'Windows'
        run: |
          $Env:ANDROID_SDK_ROOT\cmdline-tools\latest\bin\sdkmanager "platform-tools" "platforms;android-36" "build-tools;36.0.0"

      - name: Build Debug APK
        run: cd android-demo && ./gradlew clean assemble
